window.GAME_DATA=Object.freeze({
 towers:{
  doro:{name:"ドロビー塔",short:"ドロビー",cost:50,range:120,rate:28,damage:12,shot:"#2ec9ff",speed:"はやい",rating:4,role:"ボスに強い単体攻撃塔",strong:"ボス・高耐久の敵",weak:"大量の敵",description:"ボスや高耐久の敵が得意です。",recommend:"ボスの進行ルートを長く狙える場所がおすすめです。",special:"ボスへのダメージ2倍",bossDamageMultiplier:2},
  hima:{name:"ひまわり塔",short:"ひまわり",cost:75,range:180,rate:58,damage:20,shot:"#ffd22e",speed:"おそい",rating:4,role:"長射程の集団妨害塔",strong:"密集した敵・進軍の足止め",weak:"単体への瞬間火力",description:"命中時に一定確率で、対象と周囲の敵を花びらで減速します。",recommend:"長い道やカーブを見渡せる場所で集団を足止めします。",special:"成長する花びらの小範囲減速",abilityDetails:["発動率 15%","減速率 20%","持続 2.0秒","範囲 半径90"],slowChance:.15,slowFrames:120,slowMultiplier:.8,slowRadius:90},
  mike:{name:"招き猫ミケ塔",short:"ミケ",cost:120,range:0,rate:260,damage:0,shot:"#ffcf37",speed:"支援",rating:3,role:"おやつを増やす経済塔",strong:"序盤配置・長期戦",weak:"直接攻撃できません",description:"序盤に配置すると、おやつを多く獲得できるため後半が有利になります。",recommend:"早めに配置し、長いWaveでおやつを蓄えましょう。",special:"撃破報酬増加・定期おやつ生成",rewardBonus:.1,periodicSnackBase:8,periodicSnackPerLevel:3,periodicSnackInterval:260},
  witch:{name:"魔女ミケ塔",short:"魔女",cost:220,range:140,rate:50,damage:10,shot:"#a96cff",speed:"ふつう",rating:4,role:"3方向を攻撃する範囲塔",strong:"まとまった敵・複数方向",weak:"ボスへの集中攻撃",description:"一度に3方向へ魔法を放ち、敵の集団をまとめて攻撃します。",recommend:"敵が密集するカーブ付近に置くと効果的です。",special:"3方向に攻撃",multi:3},
  sign:{name:"看板猫塔",short:"看板",cost:180,range:180,rate:0,damage:0,shot:"#8ecf65",speed:"支援",rating:3,role:"周囲の攻撃力を高める補助塔",strong:"塔が集まる配置・火力支援",weak:"直接攻撃できません",description:"応援の看板で、周囲の塔の攻撃力を高めます。",recommend:"複数の攻撃塔に届く中央へ配置しましょう。",special:"周囲の塔の攻撃力+20%〜25%"},
  groom:{name:"毛づくろい猫塔",short:"毛づくろい",cost:180,range:180,rate:0,damage:0,shot:"#d9c5ff",speed:"支援",rating:3,role:"周囲の攻撃速度を高める補助塔",strong:"塔が集まる配置・手数の強化",weak:"直接攻撃できません",description:"毛づくろいの応援で、周囲の塔の攻撃間隔を短くします。",recommend:"手数を増やしたい攻撃塔の中央へ配置しましょう。",special:"近くの塔の攻撃速度+30%〜40%"},
  king:{name:"森の王様ドロビー",short:"王様",cost:300,range:240,rate:75,damage:180,shot:"#48aaff",speed:"おそい",rating:5,role:"伝説のボス特化攻撃塔",strong:"ボス・高耐久の敵",weak:"設置コスト・攻撃間隔",description:"広い範囲へ重い一撃を放ち、強敵を優先して削ります。",recommend:"ボスを長く攻撃できる中央寄りの場所がおすすめです。",special:"強力な範囲攻撃"},
  queen:{name:"ひまわり女王",short:"女王",cost:300,range:220,rate:220,damage:0,shot:"#ffd84f",speed:"支援",rating:5,role:"おやつと周囲を支える究極支援塔",strong:"長期戦・密集した塔の支援",weak:"直接攻撃できません",description:"おやつを生みながら、周囲の仲間をやさしく支援します。",recommend:"多くの塔を包める密集エリアの中央がおすすめです。",special:"おやつ生成と周囲支援"},
  star:{name:"スター塔",short:"スター",cost:350,range:330,rate:110,damage:260,shot:"#d7c6ff",speed:"とてもおそい",rating:5,role:"盾・鎧を砕く長射程攻撃塔",strong:"盾・鎧・遠くの強敵",weak:"素早い敵の集団",description:"盾や鎧へ大きなダメージを与え、時々敵を一時停止させます。",recommend:"入口から広範囲を見渡せる場所で盾を早めに削ります。",special:"盾耐久3倍・鎧2倍・10%で一時停止",shieldDamageMultiplier:3,armorDamageMultiplier:2,freezeChance:.1,freezeFrames:60,bossFreezeFrames:30,freezeCooldownFrames:180},
  peace:{name:"ドロビー＆ひまわり",short:"ふたり",cost:420,range:260,rate:520,damage:0,shot:"#fff0a8",speed:"平和",rating:5,role:"争わずに森を守る最後の特別塔",strong:"集団の押し返し・高Waveの時間稼ぎ",weak:"ボスは帰宅しません",description:"一定時間ごとに「帰ろう」を発動し、範囲内の敵に森から帰ってもらいます。",recommend:"敵が長く通る中央付近に置くと、帰宅の効果を活かせます。",special:"範囲内の敵を帰宅状態にする",returnHomeCount:4,bossRetreatFrames:150,bossRetreatDistance:2}
 },
 towerHints:{
  doro:["ボスが長く歩く場所へ置くのがおすすめです。","ボス出現前に育てると効果的です。"],
  hima:["敵が集まりやすい場所へ置くと効果的です。","花びらの足止めを、ほかの塔の攻撃時間につなげましょう。"],
  mike:["序盤に置くほど、おやつを多く増やせます。","長期戦ほど活躍するので、早めの育成がおすすめです。"],
  witch:["敵が密集するカーブ付近で3方向攻撃を活かしましょう。","ボス単体より、まとまった敵の処理が得意です。"],
  sign:["できるだけ多くの攻撃塔を範囲へ入れましょう。","同じ種類の補助効果は重複しません。","異なる補助効果は同時に受けられます。"],
  groom:["攻撃塔が集まる中央へ置くと効果的です。","同じ種類の補助効果は重複しません。","看板猫など、異なる補助効果とは同時に使えます。"],
  king:["ボスを長く狙える場所へ配置しましょう。","強化費用が高いため、ボスWaveに合わせて育てるのがおすすめです。"],
  queen:["定期的におやつを生むため、長期戦や高Wave攻略と相性が良いです。","攻撃塔を多く包める密集エリアへ置くと、攻撃速度支援が活きます。","ひまわり塔を範囲に入れると、足止め効果もさらに伸びます。"],
  star:["盾ネズミが入口に近いうちから攻撃できる場所がおすすめです。","鎧や盾が多いWaveへ向けて育てましょう。"],
  peace:["敵を倒さず、森から帰ってもらう特別な塔です。","ボスは帰宅しないため、ほかの塔と組み合わせて守りましょう。","道を長く見渡せる中央付近がおすすめです。"]
 },
 enemies:{
  forest:{name:"森ネズミ",sprite:"forest",hp:1,speed:1,reward:1,size:1,hitRadius:16},
  swift:{name:"俊足ネズミ",sprite:"swift",hp:.65,speed:1.75,reward:.85,size:.92,hitRadius:14},
  guard:{name:"どんぐり衛兵",sprite:"guard",hp:2.25,speed:.72,reward:1.65,size:1.12,hitRadius:20,armor:true},
  endlessSwift:{name:"俊足ネズミ・疾風",sprite:"swift",hp:.8,speed:2,reward:1.1,size:.94,hitRadius:14,special:true},
  shield:{name:"盾持ちネズミ",sprite:"guard",hp:1,speed:.86,reward:1.75,size:1.08,hitRadius:19,shieldHp:5,shieldBodyDamage:.12,armor:true,special:true},
  giantShield:{name:"巨大盾ネズミ",sprite:"guard",hp:1.6,speed:.62,reward:3.4,size:1.62,hitRadius:28,shieldHp:18,shieldBodyDamage:.1,protectRadius:190,protectSegments:8,protectedDamageTaken:.1,armor:true,special:true},
  piper:{name:"笛吹ネズミ",sprite:"forest",hp:1.15,speed:.82,reward:1.75,size:1.04,hitRadius:18,debuffRadius:150,attackSpeedMultiplier:.8,special:true},
  trumpet:{name:"ラッパネズミ",sprite:"forest",hp:1.35,speed:.72,reward:2.1,size:1.08,hitRadius:19,auraRadius:175,enemySpeedAura:1.16,musician:true,special:true},
  violin:{name:"バイオリンネズミ",sprite:"forest",hp:1.35,speed:.72,reward:2.1,size:1.08,hitRadius:19,auraRadius:175,damageTakenAura:.82,musician:true,special:true},
  drum:{name:"太鼓ネズミ",sprite:"guard",hp:1.55,speed:.68,reward:2.35,size:1.18,hitRadius:21,auraRadius:165,hpAura:1.15,musician:true,special:true},
  midBoss:{name:"中ボス",sprite:"guard",hp:5,speed:.58,reward:3,size:1.55,hitRadius:27,boss:true,armor:true},
  armorBoss:{name:"鎧ボス",sprite:"guard",hp:6.2,speed:.5,reward:4.5,size:1.78,hitRadius:30,boss:true,armor:true,special:true,damageTaken:.92},
  mainBoss:{name:"ネズミ王",sprite:"mouseKing",hp:10,speed:.48,reward:6,size:2.05,hitRadius:35,boss:true,royalAuraRadius:210,enemySpeedAura:1.08,damageTakenAura:.9},
  golden:{name:"金色ネズミ",sprite:"forest",hp:.55,speed:1.35,reward:1,size:.9,hitRadius:14,auraRadius:45,musician:true,special:true,golden:true}
 },
 waves:{
  chapters:[{number:1,start:1,end:3,name:"朝の森",art:"chapter1",text:"ドロビーは安心して眠れる場所を探して歩き出します。"},{number:2,start:4,end:6,name:"花畑",art:"chapter2",text:"花の香りに包まれながら、道は森の奥へ続きます。"},{number:3,start:7,end:10,name:"草原",art:"chapter3",text:"広い草原の向こうに、あたたかな灯りが見えます。"},{number:4,start:11,end:14,name:"夕暮れ",art:"chapter4",text:"夕暮れの風の中、冒険は少しずつ難しくなります。"},{number:5,start:15,end:18,name:"月夜の森",art:"chapter5",text:"月明かりの下で、最後の森を進みます。"},{number:6,start:19,end:24,name:"おうち",art:"chapter6",text:"ドロビーを迎える、安心できる場所が近づきます。"}],
  storyChapterBalance:{1:{hp:.82,count:-2,bossHp:.9},2:{hp:.88,count:-1,bossHp:.95},3:{hp:.96,count:0,bossHp:1},4:{hp:1.08,count:1,bossHp:1.08},5:{hp:1.18,count:2,bossHp:1.15},6:{hp:1.28,count:3,bossHp:1.22}},
  storyLateWaveBalance:{14:{hp:1.08,count:1,attack:1},15:{hp:1.10,count:1,attack:1},16:{hp:1.12,count:1,attack:1},17:{hp:1.14,count:2,attack:1},18:{hp:1.16,count:2,attack:1},19:{hp:1.18,count:2,attack:1},20:{hp:1.20,count:1,attack:1},21:{hp:1.22,count:2,attack:1},22:{hp:1.24,count:2,attack:1},23:{hp:1.26,count:3,attack:1},24:{hp:1.28,count:3,attack:1}},
  storyLateSpawnIntervals:{14:37,15:36,16:35,17:36,18:35,19:34,20:35,21:34,22:32,23:30,24:33}
 },
 weather:[{id:"sunny",icon:"☀",name:"晴れ",towerRate:.9,range:1,enemySpeed:1,reward:1,desc:"塔が少し元気になります。"},{id:"cloudy",icon:"☁",name:"曇り",towerRate:1,range:1,enemySpeed:1,reward:1,desc:"穏やかな天気です。"},{id:"rainy",icon:"☂",name:"雨",towerRate:1,range:.95,enemySpeed:.9,reward:1,desc:"ネズミが少し遅くなります。"},{id:"windy",icon:"風",name:"強風",towerRate:.95,range:1,enemySpeed:1.1,reward:1,desc:"風で全体が少し速くなります。"}]
});
